# Config file for automatic testing at travis-ci.org

sudo: false
language: python

matrix:
  include:
  - python: 3.4
  - python: 3.5
  - python: 3.6
  - python: 3.7
    sudo: required
    dist: xenial

install:
- pip install --upgrade pip setuptools tox tox-travis codecov coverage

script:
- tox

before_cache:
- rm -rf $HOME/.cache/pip/log

cache:
  directories:
  - $HOME/.cache/pip
